### ISSUE TITLE
Shared Components

### ISSUE THREAD

**Issue by rmzr7** [glimmerjs/glimmer.js#100]
How can we share components across multiple glimmer apps?

**Comment by hoodwink73** [comment]
Hello there

A glimmer components will depend on [arguments](https://glimmerjs.com/guides/templates-and-helpers) passed by the parent component and maintain its own *properties*, so if you make sure to follow this contract, a glimmer component can be ported to other glimmer apps, **not** ember apps.

However, if you intend to port a glimmer component into an app built on any other framework, you can choose to compile it as a [web component](https://glimmerjs.com/guides/using-glimmer-as-web-components).

> Web Components is a suite of different technologies allowing you to create reusable custom user interface components — with their functionality encapsulated away from the rest of your code — and utilize them in your web apps.

You can read more [here](https://developer.mozilla.org/en-US/docs/Web/Web_Components).

**Comment by locks** [comment]
@remzr7 At the moment there is no built-in mechanism to share components between different projects.

**Comment by tomdale** [comment]
There are at least two major things we need to implement to make this work well:

1. We need some syntax for invoking namespaced components, e.g. `<my-package::MyComponent />`.
2. We need to extend the Glimmer resolver/resolution map to include components provided by npm packages.

If someone is interested in working on this, let me know.
