### ISSUE TITLE
How do I apply routing in glimmer.js?

### ISSUE THREAD

**Issue by philipszdavido** [glimmerjs/glimmer.js#101]

**Comment by hoodwink73** [comment]
Hey Philip

Glimmerjs do not have any opinion on routers. You can use whatever suits you and your app.

The todo demo for glimmer uses [Navigo](https://github.com/krasimir/navigo). You can take a look at the code [here](https://github.com/glimmerjs/todomvc-demo/blob/master/src/ui/components/todomvc-app/component.ts#L20).

**Comment by philipszdavido** [comment]
Thanks Hoodwink

**Comment by tomdale** [comment]
@philipszdavido Closing this issue since it looks like you got a good answer from @hoodwink73, but let me know if you still have questions about this. Thanks!
