### ISSUE TITLE
Proposal to optimize build bundle size 

### ISSUE THREAD

**Issue by legaev-stas** [glimmerjs/glimmer.js#11]
At the moment (@glimmer/application@0.7.2) glimmer application creates one bundle during the build. This bundle is self-sufficient and can be used without any additional dependencies in any application. The bundle contains glimmer.js lib, 3rd party libraries and code of the component(s) it exports.

But if I want to use several bundles in one application that uses, for example, webpack, I can't optimize resulting bundle size because glimmer.js bundles are exported as single CJS module without any dependencies specified. In this case code of libraries that is provisioned with glimmer.js bundle is duplicated as many times as many glimmer bundles I use in my application.

I propose to change the build process in such a way when build produces: 
1. self-sufficient bundle (exactly the same that build process does right now)
2. Module that represent pure component(s) code with dependencies to glimmer.js library and the rest of 3rd party libs. 

Such solution allows to specify all the dependencies in package.json and export as NPM package and then projects that runs js build with webpack or another bundler can optimize final bundle size when multiple glimmer bundles are used in one application.

PS: the same issue is also relevant for case when one glimmer.js bundle should be reused inside another one.

**Comment by tomdale** [comment]
Hey @legaev-stas, thanks for opening this issue. Use cases like this are definitely something we want to support.

I think it should be straightforward to accomplish this today with the existing hooks. In your `ember-cli-build.js` file, there's a `GlimmerApp` class that defines the entire build pipeline. There are a few different hooks you can override on this class.

In this case, there's a method called `package()` that takes the final compiled JavaScript output and packages it up (using Rollup by default). If we instead want `dist` to contain just the final, unpackaged JavaScript files, we can subclass `GlimmerApp` and override `package()`, returning the input as the output:

```js
// ember-cli-build.js
'use strict';

const GlimmerApp = require('@glimmer/application-pipeline').GlimmerApp;

class ModuleApp extends GlimmerApp {
  package(jsTree) {
    return jsTree;
  }
}

module.exports = function(defaults) {
  let app = new ModuleApp(defaults, {
    // Add options here
  });

  return app.toTree();
};
```

When I run my app with this `ember-cli-build.js` configuration, I get the unpackaged output.

If you want to build *both* modules *and* the normal output (so things like `ember serve` still work), you can do something like this:

```js
'use strict';

const GlimmerApp = require('@glimmer/application-pipeline').GlimmerApp;
const mergeTrees = require('broccoli-merge-trees');

class ModuleApp extends GlimmerApp {
  package(jsTree, cssTree, publicTree, htmlTree) {
    return mergeTrees([
      super.package(...arguments),
      jsTree
    ]);
  }
}

module.exports = function(defaults) {
  let app = new ModuleApp(defaults, {
    // Add options here
  });

  return app.toTree();
};
```

**Comment by tomdale** [comment]
I think this is resolved, so I'm going to close the issue, but please let me know if there's something still missing. Thanks!
