### ISSUE TITLE
[QUEST] export `Component` from `@glimmer/component` (and `@glimmer/component/compat`)

### ISSUE THREAD

**Issue by smfoote** [glimmerjs/glimmer.js#120]
See emberjs/ember.js#16301 for the related quest issue in Ember.js.

- [ ] Support using `@glimmer/component` as an Ember addon
  - [ ] Preserve existing behavior when consumed from Glimmer.js
  - [ ] `import Component from '@glimmer/component'` provides plain JavaScript base class
  - [ ] `import Component from '@glimmer/component/compat'` provides `Ember.Object` base class
  - [ ] Base classes should import and add `componentManager` annotation when consumed from Ember
  - [ ] `CustomComponentManager` implementation should be discoverable via Ember’s container lookup (i.e. the custom component manager delegate should be registered as a `'component-manager'`)
- [ ] Lifecycle Hooks
  - [ ] static `create(injections)`
  - [ ] `didInsertElement``()`
  - [ ] `willDestroy()`
  - [ ] `didUpdate()`
  - [ ] Event delegation-invoked methods (`click()` etc.) should not be triggered
- [ ] Element Access
  - [ ] `this.bounds`
  - [ ] `this.element` computed property alias to `this.bounds`
- [ ] Arguments
  - [ ] `this.args` is available in the constructor
  - [ ] `this.args` is updated before `didUpdate` is called
  - [ ] `this.args` should not trigger an infinite re-render cycle
- [ ] Documentation
  - [ ] How to install
  - [ ] Caveats
    - [ ] Canary-only
    - [ ] Pre-1.0
  - [ ] Ember-Glimmer “compat” components
    - [ ] Outer HTML templates
    - [ ] Lifecycle hooks
    - [ ] Defining computed properties
      - [ ] How to depend on `args`

**Comment by locks** [comment]
Closing as no longer relevant. Octane shipped with `@glimmer/component`, the API of which changed significantly :) (no lifecycle hooks, for example). Thanks for the tracking issue!
