### ISSUE TITLE
Promise values & suspend rendering

### ISSUE THREAD

**Issue by jkrems** [glimmerjs/glimmer.js#122]
*I tried finding any docs on to what extend this is supported by glimmer right now but didn't have any luck.*

I'm currently working on a concept for using glimmer bytecode server-side. One important requirement is being able to suspend rendering until certain pieces of data are available. Is this something that is currently supported by glimmer? E.g. as a straw man:

```hbs
Some static bits that could be flushed right now
{{await someSignal}}
{{lazyData.foo}}
{{await anotherSignal}}
{{moreLazyData.bar}}
```

Or better yet:

```hbs
Some static bits that could be flushed right now
{{#await lazyData}}
{{foo}}
{{/await}}
{{#await moreLazyData}}
{{bar}}
{{/await}}
```

Also, it sounds like somewhere out there exists a solution to render glimmer bytecode to a stream server-side. But it seems like I can only find nebulous references to it..?

**Comment by lifeart** [comment]
@jkrems, if you need to get an html output, you may use async-dom rendering https://github.com/lifeart/async-dom

It support glimmer
