### ISSUE TITLE
[Q] Custom dirty tracking with Glimmer

### ISSUE THREAD

**Issue by evil-shrike** [glimmerjs/glimmer.js#126]
Hi

I have objects for keeping model data. I call them domain objects. They are instances of classes corresponding to model entities. Like you know Department, Employee, User and so on. These objects have nothing to do with the UI layer. But they can be used as a model for UI components.
Let's imagine we have a Glimmer component (e.g. "Editor") that should provide UI for editing some domain object (e.g. User).   
These objects already have a mechanism for dirty tracking. For every entity property in model there's a function like `prop()` that can be used as set/get accessor and on property value change there're events on object ("change" and "change:prop"). I guess it's similar to old Ember.

So now I'm thinking can I use these objects with Glimmer and how.

Can I integrate my dirty tracking with Glimmer? And how could it be approached?

**Comment by lifeart** [comment]
[glimmer playground example](https://try.glimmerjs.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTVDbiUzQ2lucHV0JTIwdmFsdWUlM0QlN0IlN0J1c2VyLmZpcnN0TmFtZSU3RCU3RCUyMG9uaW5wdXQlM0QlN0IlN0JhY3Rpb24lMjB0aGlzLnVwZGF0ZUZpZWxkJTIwJ2ZpcnN0TmFtZSclN0QlN0QlM0UlNUNuJTNDaW5wdXQlMjB2YWx1ZSUzRCU3QiU3QnVzZXIubGFzdE5hbWUlN0QlN0QlMjBvbmlucHV0JTNEJTdCJTdCYWN0aW9uJTIwdXBkYXRlRmllbGQlMjAnbGFzdE5hbWUnJTdEJTdEJTNFJTVDbiU1Q24lN0IlN0J1c2VyLmZpcnN0TmFtZSU3RCU3RCUyMCU3QiU3QnVzZXIubGFzdE5hbWUlN0QlN0QlMjIlN0QlMkMlMjJjb21wb25lbnQlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZjb21wb25lbnQudHMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyaW1wb3J0JTIwQ29tcG9uZW50JTJDJTIwJTdCJTIwdHJhY2tlZCUyMCU3RCUyMGZyb20lMjAnJTQwZ2xpbW1lciUyRmNvbXBvbmVudCclM0IlNUNuY2xhc3MlMjBVc2VyJTIwJTdCJTVDbiUyMCUyMGZpcnN0TmFtZSUyMCUzRCUyMCdhJyU1Q24lMjAlMjBsYXN0TmFtZSUyMCUzRCUyMCdiJyU1Q24lN0QlNUNubGV0JTIwdXNlciUyMCUzRCUyMG5ldyUyMFVzZXIoKSUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBleHRlbmRzJTIwQ29tcG9uZW50JTIwJTdCJTVDbiUyMCUyMCU0MHRyYWNrZWQlMjByZXZpc2lvbiUyMCUzRCUyMDAlM0IlNUNuJTIwJTIwJTQwdHJhY2tlZCgncmV2aXNpb24nKSU1Q24lMjAlMjBnZXQlMjB1c2VyKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwdXNlciUzQiU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwdXBkYXRlRmllbGQobmFtZSUyQyUyMGV2ZW50KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB1c2VyJTVCbmFtZSU1RCUyMCUzRCUyMGV2ZW50LnRhcmdldC52YWx1ZSUzQiU1Q24lMjAlMjAlMjAlMjB0aGlzLnJldmlzaW9uJTJCJTJCJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlN0QlNUQlMkMlMjJoZWxwZXJzJTIyJTNBJTVCJTVEJTdE)

**Comment by evil-shrike** [comment]
thank you! it's a clever approach, but not quite that I thought about. In this approach I'll have to use a method on a component to modify its model. I'd prefer to have dirty tracking w/o additional level of indirection: `oninput={{action user.firstName}}`
It's not about just syntax, imagine some business logic that modifies objects, it'd be cumbersome to manually call a special method on a component that owns object graph to notify engine. 
Ideally I'd like to be able to notify Glimmer from objects' internals in some way that compatible with `@track` aspect...

**Comment by lifeart** [comment]
take a look at second example, on render time you may pass component rerender-trigger-fn to your model, and this model can invoke callback to trigger rerender.
