### ISSUE TITLE
[Q] Component dynamic content and 3rd-party components

### ISSUE THREAD

**Issue by evil-shrike** [glimmerjs/glimmer.js#127]
Hi.

[Next](https://github.com/glimmerjs/glimmer.js/issues/126) question is about dynamic content. Components can have nested components obviously. Let's suppose that our App has three components: Toolbar, Main content, Footer. But App doesn't know about what main content will be, it should be specified in runtime. So we can't put component invocation in App's template.

```
<App>
  <Toolbar></Toolbar>
  <???>
  <Footer></Footer>
</App>
```
Instead I need a way to tell Glimmer - take an value from App's property and treat it as a component instance (or class!).
How can it be implemented?

Another use case would be when an object in component's property isn't a Glimmer component at all but some 3rd party component with `render` method that expects DOMElement. For example it's a vanilla js object building DOM via jQuery. How can I use it?

**Comment by lifeart** [comment]
You may create glimmer component, named "MyComponentWrappr", and use "didInsertElement" hook to invoke `YourClass.render(this.element)` method
