### ISSUE TITLE
`ember t` fails with new project on Windows

### ISSUE THREAD

**Issue by happycollision** [glimmerjs/glimmer.js#130]
Generated files during testing are using Windows file separator `\` instead of Unix style `/`. This causes bad escapes in path cache files.

(I do not know what all that means, and I could be wrong about how I am describing it).

Unfortunately, I do not know what module is actually writing this file and causing the error.

All I know is that it does not happen when you generate an Ember application. Just Glimmer.

To reproduce:
1. In Windows, follow steps one and two of Quickstart instructions at <https://glimmerjs.com>.
    `npm install -g ember-cli`
    `ember new my-app -b @glimmer/blueprint`
2. run `cd my-app/ && ember t` (instead of `ember s`)

Produces the following on my machine:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\Users\FP_production\Documents\GitHub\test>ember new my-app -b @glimmer/blueprint
installing blueprint
  create .editorconfig
  create .ember-cli
  create .watchmanconfig
  create README.md
  create config\environment.js
  create config\module-map.d.ts
  create config\resolver-configuration.d.ts
  create config\targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\robots.txt
  create src\index.ts
  create src\main.ts
  create src\ui\components\MyApp\component-test.ts
  create src\ui\components\MyApp\component.ts
  create src\ui\components\MyApp\template.hbs
  create src\ui\index.html
  create src\ui\styles\app.css
  create src\utils\test-helpers\test-helper.ts
  create testem.json
  create tsconfig.json
  create tslint.json
WARNING: Ember CLI is using the global npm, but your npm version has not yet been verified to work with the current Ember CLI release.
npm: Installed dependencies
Successfully initialized git.

c:\Users\FP_production\Documents\GitHub\test>cd my-app

c:\Users\FP_production\Documents\GitHub\test\my-app>ember t -s
Using tslint.json as the default file for linting rules
\ BuildingFinished linting 5 successfully
| BuildingBuild Error (RollupWithDependencies)

c:/Users/FP_production/Documents/GitHub/test/my-app/tmp/rollup_with_dependencies-cache_path-LKfqNewB.tmp/tests.js: Bad character escape sequence (3:15)

  1 | import './src\index.lint-test';
  2 | import './src\main.lint-test';
> 3 | import './src\ui\components\MyApp\component-test';
    |                ^
  4 | import './src\ui\components\MyApp\component-test.lint-test';
  5 | import './src\ui\components\MyApp\component.lint-test';
  6 | import './src\utils\test-helpers\test-helper.lint-test';


Stack Trace and Error Report: C:\Users\FP_PRO~1\AppData\Local\Temp/error.dump.f6672bb67d50d4fd527f59db3698d103.log
| Building
```

**Comment by russoturisto** [comment]
Same exact error, running on Windows 10

**Comment by russoturisto** [comment]
This hack fixed it:

in node_modules/@glimmer/application-pipeline/dist/lib/broccoli/test-entrypoint-builder.js changed the build() method to hack the paths:

build() {
        let testDir = this.inputPaths[0];
        let testFiles = walkSync(testDir);
        function isTest({ name }) { return name.match(/\-test$/); }
        function asImportStatement({ dir, name }) {
            let testDirRelativePath = `./${dir.replace('\\', '/')}/${name}`;
            return `import '${testDirRelativePath}';\n`;
        }
        let contents = testFiles.map(path.parse).filter(isTest).map(asImportStatement).join('');
        fs.writeFileSync(path.win32.join(this.outputPath, 'tests.js').replace('\\', '/'), contents, { encoding: 'utf8' });
    }

Thanks, :)

**Comment by bhullarg** [comment]
Raised PR to fix the issue: https://github.com/glimmerjs/glimmer-application-pipeline/pull/156

**Comment by locks** [comment]
Fix PR has been merged.
