### ISSUE TITLE
The Glimmer blueprints do not include a default .travis.yml as the Ember app do.

### ISSUE THREAD

**Issue by givanse** [glimmerjs/glimmer.js#137]
A Glimmer app generated with the command ember new my-app -b @glimmer/blueprint will not have a .travis.yml config file. Maybe it is intentional? In which case we can close this ticket.

**Comment by locks** [comment]
The repo is https://github.com/glimmerjs/glimmer-blueprint/issues @givanse 🙈 Don't you need useful tests to make Travis CI useful?

**Comment by givanse** [comment]
Okay, I see in that repo the issue about tests: https://github.com/glimmerjs/glimmer-blueprint/issues/26

Also, the README says:

> Attention
> This repo has been consolidated into the Glimmer.js monorepo. The exact code can be found here.
> Please open up any issues related to Glimmer applications here. We're sorry for any inconvenience.

So, this repos still is the right location for blueprint's issues, right? Because the code is in `glimmerjs/glimmer.js/packages/@glimmer/blueprint/`

**Comment by locks** [comment]
I believe it was intentional, and given the current CI climate, it may not be the direction we want to go with. Thanks for bringing it up.
