### ISSUE TITLE
Owner Entanglement

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer.js#146]
Currently `getOwner` and `setOwner` are used within the component manager. This is an issue because this creates a coupling between the glimmer component manager and `@glimmer/di`. To allow for "Glimmer Components in Ember" we need to remove this entanglement and just have the environment define what it means to set/get the owner.

- [ ] move `getOwner` to the environment
- [ ] move `setOwner` to the environment

**Comment by locks** [comment]
Related PR has been merged.
