### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by scmmmh** [glimmerjs/glimmer.js#162]
Hello,

When running "ember serve" I am seeing the following circular dependencies in the build log:

Rollup warning:  Circular dependency: node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/dom/helper.js -> node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/compat/svg-inner-html-fix.js -> node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/dom/helper.js
Rollup warning:  Circular dependency: node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/append.js -> node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/update.js -> node_modules/@glimmer/component/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/append.js
Rollup warning:  Circular dependency: node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/dom/helper.js -> node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/compat/svg-inner-html-fix.js -> node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/dom/helper.js
Rollup warning:  Circular dependency: node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/append.js -> node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/update.js -> node_modules/@glimmer/application/node_modules/@glimmer/runtime/dist/modules/es2017/lib/vm/append.js
Rollup warning:  Circular dependency: node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/opcode-builder.js -> node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/wrapped-component.js -> node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/compiler.js -> node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/opcode-builder.js
Rollup warning:  Circular dependency: node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/compiler.js -> node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/compile.js -> node_modules/@glimmer/application/node_modules/@glimmer/opcode-compiler/dist/modules/es2017/lib/compiler.js

The application builds and runs fine, although the build server will crash every few builds with an out-of-memory error (unsure if this is related or not).

Please let me know if you need any further debug information.

**Comment by leeoniya** [comment]
see https://github.com/rollup/rollup/issues/2271

**Comment by scmmmh** [comment]
Thank you for the clarification.
