### ISSUE TITLE
What is correct the syntax for: Passing Data To Component's @ (at) arguments?

### ISSUE THREAD

**Issue by givanse** [glimmerjs/glimmer.js#164]
When following the docs ([quickstart / testing](https://glimmerjs.com/guides/testing)) I see the error

> You tried to reference {{foo}} from the test-container template, which doesn't have an associated component class.

```
this.foo = 'bar';
await render(hbs`<MyComponent><p>{{this.foo}}</p></MyComponent>`);
```

Based on this issue https://github.com/glimmerjs/glimmer.js/issues/14 (PR https://github.com/glimmerjs/glimmer-test-helpers/pull/4), that syntax used to work.

Looks like this PR https://github.com/glimmerjs/glimmer.js/pull/51 removed that capability?

**Comment by rwjblue** [comment]
Would you mind creating a repo with a reproduction of this? I believe that it should work properly and I'm not sure whats going on...

**Comment by givanse** [comment]
Turns out this was caused by `@glimmer/test-helpers ^0.30.3`, bumping to `^0.31.1` resolved the problem.
Repro: https://github.com/givanse/glimmer-issue-164
