### ISSUE TITLE
[Regression] Auto-tracked `this.args` don't work in Ember

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer.js#181]
It seems that there is a regression of #142 in the Ember implementation. The arg's property needs to be special cased to push its tag, if it's being consumed.

I think this is a [repro](https://github.com/Addepar/emberconf-schedule-2019/blob/master/app/components/conference-session.js#L8-L12)

/cc @mixonic @kpfefferle

**Comment by rwjblue** [comment]
https://github.com/glimmerjs/glimmer.js/pull/180 Is attempting to fix this
