### ISSUE TITLE
didInsertElement not firing

### ISSUE THREAD

**Issue by IAmJulianAcosta** [glimmerjs/glimmer.js#184]
Hi, I'm just trying glimmer with octane, but I can't make work the lifecycle hooks to work.

Any reason why this could be happening?

`test-component.js`:
```
import Component from '@glimmer/component';

export default class TestComponent extends Component {
  didCreateComponent() {
    alert();
  }
}

```

Versions:
```
Ember      : 3.10.0-canary+c96cc702
Ember Data : 3.9.0-canary
@glimmer/component: ^0.14.0-alpha.4
```

**Comment by josemarluedke** [comment]
The hooks you have referred don't exist in glimmer per [RFC #416](https://github.com/emberjs/rfcs/blob/master/text/0416-glimmer-components.md).

Glimmer components have the following interface:

```ts
interface GlimmerComponent<T = object> {
  args: T;

  isDestroying: boolean;
  isDestroyed: boolean;

  constructor(owner: Opaque, args: T): void;
  willDestroy(): void;
}
```

With that, there are only two hooks: `constructor` and `willDestroy`. 

I would suggest taking a look at [RFC #0415 (Render Element Modifiers)](https://github.com/emberjs/rfcs/blob/master/text/0415-render-element-modifiers.md)

**Comment by IAmJulianAcosta** [comment]
Okay, will take a look! Thanks!

PS: Docs will be outdated because of this changes :)
