### ISSUE TITLE
glimmer-component blueprint issue

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer.js#186]
from `"@glimmer/blueprint": "~0.14.0-alpha.4"`

`ember g glimmer-component component-name`

generate classic component structure, instead of MU-like

**Comment by lifeart** [comment]
also, rebulds won't work on windows

**Comment by rwjblue** [comment]
Seems like this conditional is not working properly

https://github.com/glimmerjs/glimmer.js/blob/bea818e085787c21665ca3ee72fbb3803ac72b4a/packages/%40glimmer/component/blueprints/glimmer-component/index.js#L29

**Comment by lifeart** [comment]
yeah, `isExperimentEnabled("MODULE_UNIFICATION")` return false for default blueprint
