### ISSUE TITLE
Build fails for new App on Windows

### ISSUE THREAD

**Issue by Bernhard---H** [glimmerjs/glimmer.js#210]
Unfortionally this fails under windows:

```sh
npm install -g ember-cli
ember new my-app -b @glimmer/blueprint
cd my-app/ && ember s
```

## Fix
Fortionally, this has been addressed and this minor change in the blueprint's package.json resolved the issue for me:
```diff
// package.json
+ "@glimmer/application-pipeline": "^0.15.0",
- "@glimmer/application-pipeline": "^0.13.0",
```

Would it be possible to publish 0.13.1 of the blueprint, so nobody else has to resolve this issue?

## Related
#130 `ember t` fails with new project on Windows

**Comment by rwjblue** [comment]
The latest blueprint is 0.14.0-alpha.13, and should include the update for `@glimmer/application-pipeline` ([see here](https://github.com/glimmerjs/glimmer.js/blob/bdf1ad10c432892933ba22ae6fb84e33f71d3008/packages/%40glimmer/blueprint/files/package.json#L18)). We are working to drop the `-alpha` soon.

**Comment by Bernhard---H** [comment]
ok thx
