### ISSUE TITLE
Module '@glimmer/tracking' not found after update to @glimmer/component-1.0.0-beta.1

### ISSUE THREAD

**Issue by fpauser** [glimmerjs/glimmer.js#219]
Updated `@glimmer/component` to 1.0.0-beta.1 to get rid of the `simple-dom` missing-type-definition-errors and cannot import `tracked` properly now:

```typescript
import { tracked } from '@glimmer/tracking';
```

```
app/components/ui-input.ts:4:25 - error TS2307: Cannot find module '@glimmer/tracking'
```

**Comment by pzuraq** [comment]
We're working on this! You'll need to install the `@glimmer/tracking` package in order to get its types, and it should be working in the next beta.

**Comment by fpauser** [comment]
Just realized that the new beta is out - all fine now!
