### ISSUE TITLE
Unable to start freshly generated app with v1.0.0-beta.3

### ISSUE THREAD

**Issue by john-griffin** [glimmerjs/glimmer.js#228]
I wanted to test out the changes in `v1.0.0-beta.3` so I cloned this repo locally and ran the following to generate and run a new glimmer app.

``` sh
ember new new-glimmer-app -b ./glimmer.js/packages/@glimmer/blueprint
cd new-glimmer-app
npm start
```

Which produced the following error:

```
Build Error (RollupWithDependencies)

'setPropertyDidChange' is not exported by node_modules/@glimmer/component/dist/modules/es2017/index.js


Stack Trace and Error Report: /var/folders/b5/xtgx28d1475gcmvd_d7xfphw0000gn/T/error.dump.89b04f72c6e82676b7dd68c9f3c71820.log
(node:2493) UnhandledPromiseRejectionWarning: Error: 'setPropertyDidChange' is not exported by node_modules/@glimmer/component/dist/modules/es2017/index.js```

**Comment by pzuraq** [comment]
It looks like the import needs to be updated to pull it from `@glimmer/tracking` in the blueprint

**Comment by john-griffin** [comment]
Thanks. I just ran `npm install @glimmer/tracking --dev` in the generated app but still get the same error.

**Comment by pzuraq** [comment]
Did you change the import itself? Some of your code is attempting to import from `@glimmer/component`

**Comment by john-griffin** [comment]
Nothing in the generated code is importing `setPropertyDidChange` from `@glimmer/component`.

I was able to narrow it down to the `@glimmer/test-helpers` package. Removing that allows the app to at least build.

**Comment by pzuraq** [comment]
The usage I was thinking of should be here: https://github.com/glimmerjs/glimmer.js/blob/c7673bfc06bf550acb5a51962f01a95982b23ae0/packages/%40glimmer/blueprint/files/src/index.ts#L7

It looks like that has been updated though. I'm not sure if the test helpers have been updated, I think that's a separate repo, will check when I get a chance.

**Comment by john-griffin** [comment]
Looks like you already the work here https://github.com/glimmerjs/glimmer-test-helpers/pull/9
