### ISSUE TITLE
The option '--web-component' is not registered with the new command

### ISSUE THREAD

**Issue by jamesdixon** [glimmerjs/glimmer.js#275]
Hi,

I installed Ember CLI 2.13.0-beta.3 and when running the following:

`ember new meet-n-greet-widget -b @glimmer/blueprint --web-component`

the application is created, but I see the following warning:

`The option '--web-component' is not registered with the new command. Run `ember new --help` for a list of supported options.`

Version info:

```
$ember -v
ember-cli: 2.13.0-beta.3
node: 7.8.0
os: darwin x64
```

Thanks!

**Comment by locks** [comment]
Tracked at https://github.com/ember-cli/ember-cli/issues/6948 !
