### ISSUE TITLE
Warnings about unmet peer dependencies

### ISSUE THREAD

**Issue by synaptiko** [glimmerjs/glimmer.js#279]
**Steps to reproduce:**
- `ember new test-gjs -b @glimmer/blueprint`
- `cd test-gjs && rm -rf node_modules yarn.lock`
- `yarn`

I can see those warnings in the output of `yarn`:
```
warning "@glimmer/inline-precompile@1.0.1" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/test-helpers@0.30.0" has unmet peer dependency "@glimmer/component@>= 0.4.0".
```

Is it something I should worry about?

I tried to run:
```
yarn add -D @glimmer/component @glimmer/compiler
```

which installed versions:
```
$ grep -E "component|compiler" package.json
    "@glimmer/compiler": "^0.29.3",
    "@glimmer/component": "^0.6.0",
```

but the warning for `@glimmer/test-helpers` is still there…

---

```
$ ember -v
2.15.1
$ yarn -v
1.1.0
```

**Comment by rwjblue** [comment]
We've done a complete revamp in the lead up to 2.x, closing as I believe these warnings are addressed now.
