### ISSUE TITLE
I'd like Unit Tests instead of Integration Tests

### ISSUE THREAD

**Issue by forbesmyester** [glimmerjs/glimmer.js#28]
I understand that having a few integration tests through the browser is desirable, but am not at all sure they should be ran on `npm test`.

Standard unit tests are faster, easier to debug and have a far better developer experience. I think we should consider having them out of the box instead of integration tests which probably won't due to individual workstation configuration.

Failing that easily find-able instructions on how to switch.

**Comment by rwjblue** [comment]
Sadly the words "unit test" and "integration test" have fairly little meaning (or rather they mean many different things to different people). Can you describe the type of test you are trying to write (possibly pseudo code)?

**Comment by forbesmyester** [comment]
That is true.

I want to write most of my tests so that they run without any side effects
and do not depend on any external state, they should run in as short a time
as possible and should not steal the focus (as in window which is active)
away from my editor. These tests also tend to be super easier to write and
tend to make more of the app stateless and therefore easier to maintain in
future.

Later on I would probably write what I would call integration tests (that
test through the browser and interact with real databases) but not as a
first port of call.

Thanks
