### ISSUE TITLE
Un-pin version of ember-cli-typescript

### ISSUE THREAD

**Issue by ondrejsevcik** [glimmerjs/glimmer.js#296]
Hi, is it required to have the `ember-cli-typescript` pinned to a specific version? It would be better to use a version range to allow for a deps flattening.

https://github.com/glimmerjs/glimmer.js/blob/4f1029e7a87089aeff36627ad821c1ce1ce2b27e/packages/%40glimmer/component/package.json#L40

**Comment by rwjblue** [comment]
Nope, I don't think we need to be pinned to a specific version (`^` would be fine). Mind sending in a PR?
