### ISSUE TITLE
`@glimmer/validator` including twise error (only for npm, 2.0.0-beta.8)

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer.js#303]
![image](https://user-images.githubusercontent.com/1360552/92306756-4469ae00-ef9a-11ea-9e8d-2536e515a7ef.png)

I'm trying to add new version of glimmer.js to the benchmark https://github.com/krausest/js-framework-benchmark/pull/786 
And I face this issue If I'm using npm for package installation.

If I'm using yarn for packages installation - all ok

**Comment by john-griffin** [comment]
Also just hit this. Seems like `@glimmer/core@2.0.0-beta.8` is locked on `@glimmer/validator` version `0.61.1`, while `@glimmer/reference@^0.61.1` requires `^0.61.2`.
