### ISSUE TITLE
Blueprint doesn't generate src files

### ISSUE THREAD

**Issue by betocantu93** [glimmerjs/glimmer.js#311]
Hello, trying out glimmer blueprint with `ember new hello-world-2 -b @glimmer/blueprint` doesn't generate the src directory and so it fails to `ember s`

**Comment by drewmcdonald1337** [comment]
I ran into this, I think it's a duplicate of #229 .

**Comment by locks** [comment]
I believe this applied to pre-v2 versions, so no longer relevant!
