### ISSUE TITLE
Passing parameters to named blocks causes Parse Error

### ISSUE THREAD

**Issue by shadyvd** [glimmerjs/glimmer.js#346]
Attempting to pass a parameter to a named block in a `{{yield to="named_block" "xyz"}}` fashion causes the HBS Parser to throw an exception:
`Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', got 'STRING'
`

This is easily reproducible: [Glimmer Playground Example](https://try.glimmerjs.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDaDElM0VXZWxjb21lJTIwdG8lMjBHbGltbWVyISUzQyUyRmgxJTNFJTVDbiUzQ1RhYiUyMGFzJTIwJTdDdGFnJTdDJTNFJTVDbiUyMCUyMCUzQyUzQXRhYkl0ZW0lMjBhcyUyMCU3Q1RhYkl0ZW0lN0MlM0UlNUNuJTIwJTIwJTIwJTIwJTNDVGFiSXRlbSUyMCU0MG5hbWUlM0QlNUMlMjJmaXJzdCU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlM0MlMkYlM0F0YWJJdGVtJTNFJTVDbiUzQyUyRlRhYiUzRSUyMiU3RCUyQyUyMmNvbXBvbmVudCUyMiUzQSU3QiUyMmZpbGVOYW1lJTIyJTNBJTIyc3JjJTJGdWklMkZjb21wb25lbnRzJTJGR2xpbW1lckFwcCUyRmNvbXBvbmVudC50cyUyMiUyQyUyMnNvdXJjZVRleHQlMjIlM0ElMjJpbXBvcnQlMjBDb21wb25lbnQlMjBmcm9tJTIwJyU0MGdsaW1tZXIlMkZjb21wb25lbnQnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMGV4dGVuZHMlMjBDb21wb25lbnQlMjAlN0IlNUNuJTdEJTIyJTdEJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMlRhYiUyMiUyQyUyMnRlbXBsYXRlJTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZUYWIlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDZGl2JTNFJTVDbiUyMCUyMFRoaXMlMjBpcyUyMHRhYiUyMGNvbXBvbmVudCU1Q24lMjAlMjAlN0IlN0J5aWVsZCUyMHRvJTNEJTVDJTIydGFiSXRlbSU1QyUyMiUyMCU1QyUyMkhlbGxvJTVDJTIyJTdEJTdEJTVDbiUzQyUyRmRpdiUzRSUyMiU3RCUyQyUyMmNvbXBvbmVudCUyMiUzQSU3QiUyMmZpbGVOYW1lJTIyJTNBJTIyc3JjJTJGdWklMkZjb21wb25lbnRzJTJGVGFiJTJGY29tcG9uZW50LnRzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMmltcG9ydCUyMENvbXBvbmVudCUyMGZyb20lMjAlNUMlMjIlNDBnbGltbWVyJTJGY29tcG9uZW50JTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBleHRlbmRzJTIwQ29tcG9uZW50JTIwJTdCJTVDbiU3RCUzQiUyMiU3RCU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJUYWJJdGVtJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRlRhYkl0ZW0lMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDZGl2JTNFJTVDbiUyMCUyMFRoaXMlMjBpcyUyMGElMjBUYWJJdGVtJTIwJTdCJTdCJTQwbmFtZSU3RCU3RCU1Q24lM0MlMkZkaXYlM0UlMjIlN0QlMkMlMjJjb21wb25lbnQlMjIlM0FudWxsJTdEJTVEJTJDJTIyaGVscGVycyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJoYXNoJTIyJTJDJTIyaGVscGVyJTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZoYXNoJTJGaGVscGVyLnRzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGhlbHBlcihhcmdzJTJDJTIwbmFtZWQpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMG5hbWVkJTNCJTVDbiU3RCUyMiU3RCU3RCU1RCU3RA==)

Stack:
Ember 3.26.1
Ember CLI 3.26.1
Glimmer/Component: 1.0.4

**Comment by pzuraq** [comment]
I believe this is an issue with the Jison parser. Positional arguments have to come first, before named arguments, so you should be able to do:

```hbs
{{yield "xyz" to="named_block"}}
```

Unfortunately I don't think we can really give a better error message for this, because it occurs within Jison, which has very few if any abilities to hook into errors. We've been discussing rewriting that portion of the parser/compiler into something more modern which we would have more control over for that reason.

**Comment by shadyvd** [comment]
That worked for me. Thank you.
