### ISSUE TITLE
Can Ember addons be used in glimmer?

### ISSUE THREAD

**Issue by jajacobs** [glimmerjs/glimmer.js#4]

**Comment by rwjblue** [comment]
yes

**Comment by rwjblue** [comment]
and no 😈

**Comment by ef4** [comment]
glimmer.js has no stability policy or stable releases at this time. Those things are a critical ingredient for keeping an addon ecosystem working and healthy.

As parts of glimmer.js achieve stability, they are likely to just become parts of Ember, at which point addons will necessarily work with them.

**Comment by tomdale** [comment]
At this time, Ember addons will almost certainly not work with a Glimmer.js app, no. Over time, I suspect that there will be addons that are scoped to just providing components that could work in both, but the APIs to support that don't exist today.
