### ISSUE TITLE
Confusing livereload server address is printed first

### ISSUE THREAD

**Issue by tomdale** [glimmerjs/glimmer.js#48]
Got some feedback from someone playing with Glimmer.js for the first time. On booting the development server, the first message printed to stdout is:

```
Livereload server on http://localhost:7020
```

This is confusing because it seems like this is the URL you are supposed to open in your browser. However, if you open it, it will just print a JSON payload instead of the app you're expecting. The URL the livereload server is listening on is an implementation detail that we don't need to surface to users; particularly as the first thing they see.

**Comment by rwjblue** [comment]
This is something we need to fix in ember-cli I believe.

**Comment by Turbo87** [comment]
resolved by https://github.com/ember-cli/ember-cli/pull/7406
