### ISSUE TITLE
Unable to run ember s in newly created Glimmer project

### ISSUE THREAD

**Issue by kevgathuku** [glimmerjs/glimmer.js#76]
Hello,
I'm just trying out the Glimmer by following the `Getting Started` guide on the website.
After generating a new project and trying to run `ember s` to start the server, I get a blank terminal output, like it's trying to process something. 
After a while, if I cancel the `ember s` command, I get this output:
```
Looks like you have a different program called watchman.
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:7020
cleaning up...
Cannot stop: not the current node.
Cannot stop: not the current node.
Cannot stop: not the current node.
Build Canceled
```
I have watchman installed via brew

Output of `ember --version`:
```
ember-cli: 2.16.2
node: 6.9.1
os: darwin x64
```

Output of `watchman --version`
`4.9.0`

Output of `which -a watchman`:
`/usr/local/bin/watchman`

It seems the issue might be with the `ember` command, but I'm not sure the right place to report it.

At this point I'm not sure what else to try to get the basic version working. Any ideas would be very welcome 😄

**Comment by locks** [comment]
Couldn't reproduce on my machine:

```
$ ember --version
ember-cli: 2.16.2
node: 8.7.0
os: darwin x64
```

**Comment by kevgathuku** [comment]
Unfortunately, removing and re-installing `ember-cli` doesn't work.
I'm still facing the same issue

**Comment by kevgathuku** [comment]
Solved by re-installing `watchman`
https://github.com/ember-cli/ember-cli/issues/7448

**Comment by locks** [comment]
Thank you for the follow up, and sorry for the inconvenience while getting started. Hope you have a smoother Ember sailing going forward :)
