### ISSUE TITLE
Nested components - help needed

### ISSUE THREAD

**Issue by jpincas** [glimmerjs/glimmer.js#79]
Not sure if this is the right place to ask - I can't find any other discussion channels/forums for Glimmer.js yet.

I'm trying to achieve something like:
```
<TabComponent>
  <MyComponentA />
  <MyComponentB />
</TabComponent>
```

where the TabComponent would be able to iterate over child components and display them or not.

I've searched through documentation, but I'm not sure if this is a Glimmer thing or an Ember thing.  I have a vague notion that I should be using `yield` but can't seem to find anything that tackles what I'm trying to do.

So, how do I access nested child components from the parent component.   Are there any docs that explain how to do this?

**Comment by josemarluedke** [comment]
Hello @jpincas I believe you are looking for yielding a component. 

I created a demo here: http://tinyurl.com/y8kllzd2. Note that I created the hash helper to be able to yield the components. Also, I'm not sure of how much these APIs are public or not. Someone else can shine in and confirm if that is the right approach.

**Comment by tomdale** [comment]
@josemarluedke Everything in your example is public API. Nice work!

**Comment by locks** [comment]
I am closing the issue as @josemarluedke provided a valid answer, and we usually reserve issue trackers for bugs. If you still have need for help, join us on Slack or post to https://stackoverflow.com/tags/glimmer.js. Thank you!
