### ISSUE TITLE
Turning Glimmer Component into a generic class

### ISSUE THREAD

**Issue by dkundel** [glimmerjs/glimmer.js#94]
Hi everyone,

I'm currently taking a stab at my first Glimmer application. One thing I realized is that `Component` right now isn't a generic class. I think it would be useful to turn it into a generic to be able to type the arguments. This could later also help since we could write an extension that enables type checking on the handlebar templates for valid arguments.
I would be happy to do the work on turning this into a generic class. We could type the default still as `any` to make it backwards compatible. 

Let me know what you think :)

Cheers,
Dominik

Some code for explanation.

1. Turn class into generic:

```ts
class Component<TComponentArguments = any> {
  get args() {
    return this.__args__;
  }
  private __args__: TComponentArguments | null = null;

  // omitted rest of code
}
```

2. Usage:

```hbs
{{!--  template.hbs --}}
<SomeComponent @example="foo" />
```

```ts
interface SomeComponentArguments {
  example: string;
}
class SomeComponent extends Component<SomeComponentArguments> {
  didInsertElement() {
    const example = this.args.example;
    console.log(this.args.foo); // will break since foo is not a property of SomeComponentArguments
  }
}
```

**Comment by tschoartschi** [comment]
This sounds like an interesting idea 👍 I think the best way to get this going is to create a PR

**Comment by t-sauer** [comment]
What are the advantages over typing `args` in the class itself?

E.g.

```typescript
class MyComponent extends Component {
  args: {
    example: number;
  }
}
```

**Comment by tschoartschi** [comment]
@t-sauer I didn't know that it is possible to define `args` when there is already a `get args()`. I need to test if this wouldn't change behavior. If it works I also like your solution since its less overhead to write. I'm not sure which version is more sound. But type check handlebar templates, as well as code completion and IntelliSense in templates, would be a very nice feature 😃

**Comment by locks** [comment]
@tschoartschi what is the relationship between generic Component and template validation?

**Comment by dkundel** [comment]
Hey! It wouldn't be something that we would get directly out of the box but it would help setting the foundation for it. It would require Glimmer to have its own language server similar to [`@angular/language-server`](https://npm.im/@angular/language-server). The result could be an extension [similar to this one for Angular and VS Code](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template). It shows the concept pretty nicely.

I'll see if I can get a PR for the generic part done in the next two weeks :) holidays and stuff ^^
